---
title: "Publications"
output: html_document
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>
8-) __Cross-species comparative connectomics reveals the evolution of an olfactory circuit__, Roberts et al., 2025, (bioRxiv link: https://www.biorxiv.org/content/10.1101/2025.06.11.659158v1.abstract, *under review*)

7) __Sharp habitat shifts, evolutionary tipping points and rescue: quantifying the perilous path of a specialist species toward a refugium in a changing environment__, L. Dekens, 2024, (*Theoretical Population Biology*, doi: https://doi.org/10.1016/j.tpb.2024.09.001)

6) __The best of both worlds: combining population genetic and quantitative genetic models__, L. Dekens, S.P. Otto and V. Calvez, 2022, *Theoretical Population Biology*, doi: https://doi.org/10.1016/j.tpb.2022.10.002, arXiv link: https://arxiv.org/abs/2111.11142)

5) __Dynamics of dirac concentrations in the evolution of quantitative alleles with sexual reproduction__, L. Dekens and S. Mirrahimi, 2022, *Nonlinearity*, doi: https://doi.org/10.1088/1361-6544/ac91bb, arXiv link: https://arxiv.org/abs/2111.14814)

4) __Evolutionary dynamics of complex traits in sexual populations in a heterogeneous environment: how normal?__, L. Dekens, 2022, *Journal of Mathematical Biology* (doi: 10.1007/s00285-021-01712-0, read-only published version: https://rdcu.be/cF7gg, arXiv link: https://arxiv.org/pdf/2012.10115.pdf)

3) __Front propagation of a sexual population with evolution of dispersion: a formal analysis__, L. Dekens and F.Lavigne, 2021, *SIAM Journal of Applied Mathematics* (doi: https://doi.org/10.1137/20M1356129, arXiv link: https://arxiv.org/pdf/2105.02523.pdf)

2) __Influence of the mode of reproduction on dispersal evolution during species invasion__, V.  Calvez, J.  Crevat, L. Dekens, B.  Fabrèges, F.  Kuczma, F.  Lavigne and G.  Raoul, 2020, *ESAIM: ProcS 67 120-134* (doi:  		https://doi.org/10.1051/proc/202067008, pdf: https://www.esaim-proc.org/articles/proc/pdf/2020/01/proc206708.pdf)

1) __Multivariate distribution correction of climate model outputs: A generalization of quantile mapping approaches.__ L. Dekens, S. Parey, M. Grandjacques and D. Dacunha‐Castelle. , 2017, *Environmetrics* (doi: https://doi.org/10.1002/env.2454)
