---
title: "Talks in international conferences and workshops"
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>
1) *Society of Mathematical Biology 2021* (Talk Award for Population Dynamics & Evolution)
2) *Virtual Evolution 2021*
3) *Non-Local Models arising from Biology* (CIRM, Marseille, October 2021)
4) *Mathematical models of Ecology and Evolution* (Institut Henri Poincaré, Paris, March 2022)
5) *Evolution 2022* (Cleveland, USA, June 2022)
6) *MMEE 2022* (Reading, UK, July 2022)
7) *Congress of the European Society of Evolutionary Biology 2022* (Praha, Czech Republic, August 2022)
8) *14th Congress of the European Society of Mathematical Biology 2022* (Heidelberg, Germany, September 2022)
9) *ANR Integro-Differential Equations from EVolutionary biology* (IMAG,  Montpellier, October 2022)
10) *Mathematical Models of Evolutionary Rescue* (Max Planck Institute for Evolutionary Biology,  Plön, Germany, June 2023)
11) *RMR 2023 : Modèles mathématiques pour la biologie et la santé* (LMRS, Rouen, June 2023)
12) *Evolution 2023* (Albuquerque, USA, June 2023)
13) *PDEs seminar* (IMB Université de Bordeaux, December 2023)
14) *Mathematical Models of Ecology and Evolution* (Wien, Austria, July 2024)
15) *Dynamical Models Arising from Biology* (Banff, Canada, October 2024)
16) *Analysis, stochastic phenomena and applications" seminar* (LMBA, Brest, December 2025)
17) *Mathematical Biology and Ecology seminar* (Wolfson Center for Mathematical Biology, University of Oxford, UK, February 2026)
18) *SBIDER seminar* (The Zeeman Institute for Systems Biology & Infectious Disease Epidemiology Research, University of Warwick, UK, June 2026)
